# Copyright (C) 2015-Present Pivotal Software, Inc. All rights reserved.
# This program and the accompanying materials are made available under the terms of the under the Apache License, Version 2.0 (the "License‚Äù); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

---
name: service-metrics

director_uuid: <director UUID>

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

releases:
- name: service-metrics
  version: latest
- name: loggregator
  version: 77
- name: consul
  version: 159

instance_groups:
- name: service-metrics
  instances: 1
  stemcell: trusty
  vm_type: <vm type>
  networks:
  - name: <network>
  azs:
  - <availability zone>
  jobs:
  - name: service-metrics
    release: service-metrics
    properties:
      service_metrics:
        origin: metrics-source
        execution_interval_seconds: 5
        metrics_command: /bin/echo
        metrics_command_args:
        - -n
        - '[{"key":"service-dummy","value":99,"unit":"metric"}]'
        monit_dependencies: []

  - name: metron_agent
    release: loggregator
    properties:
      metron_agent:
        zone: <availability zone>
        deployment: <deployment name>
      metron_endpoint:
        shared_secret: <secret>
      loggregator:
        tls:
          ca_cert: |
            -----BEGIN CERTIFICATE-----
            <loggregator root certificate>
            -----END CERTIFICATE-----
          metron:
            cert: |
              -----BEGIN CERTIFICATE-----
              <loggregator client certificate>
              -----END CERTIFICATE-----
            key: |
              -----BEGIN RSA PRIVATE KEY-----
              <loggregator client private key>
              -----END RSA PRIVATE KEY-----

  - name: consul_agent
    release: consul
    consumes:
      consul:
        from: consul_server
        deployment: <cf deployment name>
    properties:
      consul:
        agent:
          domain: <consul domain suffix for DNS>
          servers:
            lan:
            - <consul LAN server IP addresses>
        agent_cert: |+
          -----BEGIN CERTIFICATE-----
          <consul agent certificate>
          -----END CERTIFICATE-----
        agent_key: |+
          -----BEGIN RSA PRIVATE KEY-----
          <consul agent private key>
          -----END RSA PRIVATE KEY-----
        ca_cert: |+
          -----BEGIN CERTIFICATE-----
          <consul agent root certificate>
          -----END CERTIFICATE-----
        encrypt_keys:
        - <consul encryption keys>

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
